[package]
name = "dominator-hello-world"
version = "0.1.0"
edition = "2021"

[dependencies]
dominator = "0.5.34"
futures-signals = "0.3.33"
log = "0.4.21"
once_cell = "1.19.0"
reqwasm = "0.5.0"
wasm-bindgen = "0.2.92"
wasm-logger = "0.2.0"
web-sys = "0.3.69"
